name    'erwbgy-runit'
version '0.4.1'
source 'git@github.com:erwbgy/puppet-runit.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Puppet module to create user services linked to init'
description 'Installs and configures Runit and sets up managed services for normal users'
project_page 'https://github.com/erwbgy/puppet-runit'
